create table if not exists public.datasets
(
 id bigint generated by default as identity
 constraint "PK_datasets"
 primary key,
 "Document" bigint not null,
 "NextDocument" bigint not null,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone
);

alter table public.datasets
 owner to postgres;

create table if not exists public.locations
(
 id bigint generated by default as identity
 constraint "PK_locations"
 primary key,
 "Address" text not null,
 "Latitude" double precision not null,
 "Longitude" double precision not null,
 "PostalCode" text not null,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone
);

alter table public.locations
 owner to postgres;

create table if not exists public.partners
(
 id uuid not null
 constraint "PK_partners"
 primary key,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone,
 "Name" text not null,
 "ApiKey" text not null,
 segmentation boolean default false not null,
 "Logo" text
);

alter table public.partners
 owner to postgres;

create table if not exists public.consumers
(
 id bigint generated by default as identity
 constraint "PK_consumers"
 primary key,
 "ExternalId" text not null,
 "Name" text not null,
 "PartnerId" uuid not null
 constraint "FK_consumers_partners_PartnerId"
 references public.partners
 on delete cascade,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone
);

alter table public.consumers
 owner to postgres;

create index if not exists "IX_consumers_PartnerId"
 on public.consumers ("PartnerId");

create table if not exists public.nifs
(
 id bigint generated by default as identity
 constraint "PK_nifs"
 primary key,
 "Number" text not null,
 "ConsumerId" bigint not null
 constraint "FK_nifs_consumers_ConsumerId"
 references public.consumers
 on delete cascade,
 "CurrencyCode" text not null,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone,
 "Type" text default 'S'::text not null
);

alter table public.nifs
 owner to postgres;

create table if not exists public.documents
(
 id bigint generated by default as identity
 constraint "PK_documents"
 primary key,
 "Year" integer not null,
 "ConsumerId" bigint not null
 constraint "FK_documents_consumers_ConsumerId"
 references public.consumers
 on delete cascade,
 "NifId" bigint not null
 constraint "FK_documents_nifs_NifId"
 references public.nifs
 on delete cascade,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone,
 "Type" text default 'SALES'::text not null
);

alter table public.documents
 owner to postgres;

create table if not exists public."CustomClearances"
(
 id bigint generated by default as identity
 constraint "PK_CustomClearances"
 primary key,
 value double precision not null,
 "DocumentId" bigint not null
 constraint "FK_CustomClearances_documents_DocumentId"
 references public.documents
 on delete cascade,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone,
 month integer default 0 not null,
 taxonomy text default ''::text not null
);

alter table public."CustomClearances"
 owner to postgres;

create index if not exists "IX_CustomClearances_DocumentId"
 on public."CustomClearances" ("DocumentId");

create table if not exists public."Dousiers"
(
 id bigint generated by default as identity
 constraint "PK_Dousiers"
 primary key,
 n1document_id bigint not null
 constraint "FK_Dousiers_documents_n1document_id"
 references public.documents
 on delete cascade,
 n2document_id bigint not null
 constraint "FK_Dousiers_documents_n2document_id"
 references public.documents
 on delete cascade,
 n3document_id bigint
 constraint "FK_Dousiers_documents_n3document_id"
 references public.documents,
 is_locked boolean not null,
 consumer_id bigint not null
 constraint "FK_Dousiers_consumers_consumer_id"
 references public.consumers
 on delete cascade,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone
);

alter table public."Dousiers"
 owner to postgres;

create table if not exists public."DousierParamaterStore"
(
 id bigint generated by default as identity
 constraint "PK_DousierParamaterStore"
 primary key,
 consumer_id bigint not null
 constraint "FK_DousierParamaterStore_consumers_consumer_id"
 references public.consumers
 on delete cascade,
 dousier_id bigint not null
 constraint "FK_DousierParamaterStore_Dousiers_dousier_id"
 references public."Dousiers"
 on delete cascade,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone,
 "Key" text default ''::text not null,
 "Value" text default ''::text not null
);

alter table public."DousierParamaterStore"
 owner to postgres;

create index if not exists "IX_DousierParamaterStore_consumer_id"
 on public."DousierParamaterStore" (consumer_id);

create index if not exists "IX_DousierParamaterStore_dousier_id"
 on public."DousierParamaterStore" (dousier_id);

create index if not exists "IX_Dousiers_consumer_id"
 on public."Dousiers" (consumer_id);

create index if not exists "IX_Dousiers_n1document_id"
 on public."Dousiers" (n1document_id);

create index if not exists "IX_Dousiers_n2document_id"
 on public."Dousiers" (n2document_id);

create index if not exists "IX_Dousiers_n3document_id"
 on public."Dousiers" (n3document_id);

create table if not exists public.accounting_customers
(
 id bigint generated by default as identity
 constraint "PK_accounting_customers"
 primary key,
 customer_id text not null,
 account_id text not null,
 customer_tax_id text not null,
 company_name text not null,
 telephone text,
 fax text,
 website text,
 email text,
 contact text,
 address_detail text not null,
 city text not null,
 postal_code text not null,
 country text not null,
 consumer_id bigint not null
 constraint "FK_accounting_customers_consumers_consumer_id"
 references public.consumers
 on delete cascade,
 document_id bigint not null
 constraint "FK_accounting_customers_documents_document_id"
 references public.documents
 on delete cascade,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone
);

alter table public.accounting_customers
 owner to postgres;

create index if not exists "IX_accounting_customers_consumer_id"
 on public.accounting_customers (consumer_id);

create index if not exists "IX_accounting_customers_document_id"
 on public.accounting_customers (document_id);

create table if not exists public.document_periods
(
 id bigint generated by default as identity
 constraint "PK_document_periods"
 primary key,
 "Month" integer not null,
 "DocumentId" bigint not null
 constraint "FK_document_periods_documents_DocumentId"
 references public.documents
 on delete cascade,
 "StartDate" timestamp with time zone not null,
 "EndDate" timestamp with time zone not null,
 "Complete" boolean not null,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone
);

alter table public.document_periods
 owner to postgres;

create index if not exists "IX_document_periods_DocumentId"
 on public.document_periods ("DocumentId");

create index if not exists "IX_documents_ConsumerId"
 on public.documents ("ConsumerId");

create index if not exists "IX_documents_NifId"
 on public.documents ("NifId");

create table if not exists public.gla_accounts
(
 id bigint generated by default as identity
 constraint "PK_gla_accounts"
 primary key,
 account_id text not null,
 account_description text not null,
 opening_debit_balance double precision not null,
 opening_credit_balance double precision not null,
 closing_debit_balance double precision not null,
 closing_credit_balance double precision not null,
 grouping_category text not null,
 grouping_code text,
 taxonomy_code integer not null,
 year integer not null,
 consumer_id bigint not null
 constraint "FK_gla_accounts_consumers_consumer_id"
 references public.consumers
 on delete cascade,
 document_id bigint not null
 constraint "FK_gla_accounts_documents_document_id"
 references public.documents
 on delete cascade,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone,
 n1 text default ''::text not null,
 n2 text default ''::text not null,
 n3 text default ''::text not null,
 n4 text default ''::text not null,
 taxonomy text default ''::text not null,
 taxonomy_class text default ''::text not null
);

alter table public.gla_accounts
 owner to postgres;

create index if not exists "IX_gla_accounts_consumer_id"
 on public.gla_accounts (consumer_id);

create index if not exists "IX_gla_accounts_document_id"
 on public.gla_accounts (document_id);

create index if not exists gla_accounts_account_id_index
 on public.gla_accounts (account_id);

create index if not exists gla_accounts_taxonomy_code_index
 on public.gla_accounts (taxonomy_code desc);

create index if not exists gla_accounts_year_index
 on public.gla_accounts (year);

create table if not exists public.gle_lines
(
 id bigint generated by default as identity
 constraint "PK_gle_lines"
 primary key,
 journal_id text not null,
 account_id text not null,
 supplier_id text,
 customer_id bigint not null
 constraint "FK_gle_lines_gla_accounts_customer_id"
 references public.gla_accounts
 on delete cascade,
 description text not null,
 transaction_id text not null,
 transaction_date timestamp with time zone not null,
 doc_archival_number text not null,
 transaction_type text not null,
 gl_posting_date timestamp with time zone not null,
 ammount double precision not null,
 type text not null,
 consumer_id bigint not null
 constraint "FK_gle_lines_consumers_consumer_id"
 references public.consumers
 on delete cascade,
 year integer not null,
 document_id bigint not null
 constraint "FK_gle_lines_documents_document_id"
 references public.documents
 on delete cascade,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone,
 gla_id bigint default 0 not null
 constraint "FK_gle_lines_gla_accounts_gla_id"
 references public.gla_accounts
 on delete cascade,
 month integer default 0 not null,
 period integer default 0 not null
);

alter table public.gle_lines
 owner to postgres;

create index if not exists "IX_gle_lines_consumer_id"
 on public.gle_lines (consumer_id);

create index if not exists "IX_gle_lines_customer_id"
 on public.gle_lines (customer_id);

create index if not exists "IX_gle_lines_document_id"
 on public.gle_lines (document_id);

create index if not exists "IX_gle_lines_gla_id"
 on public.gle_lines (gla_id);

create index if not exists gle_lines_account_id_index
 on public.gle_lines (account_id);

create index if not exists gle_lines_month_index
 on public.gle_lines (month);

create index if not exists gle_lines_transaction_type_index
 on public.gle_lines (transaction_type);

create index if not exists gle_lines_type_index
 on public.gle_lines (type);

create index if not exists gle_lines_year_index
 on public.gle_lines (year desc);

create index if not exists "IX_nifs_ConsumerId"
 on public.nifs ("ConsumerId");

create table if not exists public.pt_postal_codes
(
 id bigint generated by default as identity
 constraint "PK_pt_postal_codes"
 primary key,
 postal_designation text not null,
 postal_code text not null,
 district text not null,
 county text not null,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone
);

alter table public.pt_postal_codes
 owner to postgres;

create index if not exists pt_postal_codes_postal_code_index
 on public.pt_postal_codes (postal_code);

create table if not exists public.saft_customers
(
 id bigint generated by default as identity
 constraint "PK_saft_customers"
 primary key,
 internal_id text not null,
 name text not null,
 country text not null,
 latitude double precision not null,
 longitude double precision not null,
 address text not null,
 city text not null,
 consumer_id bigint not null
 constraint "FK_saft_customers_consumers_consumer_id"
 references public.consumers
 on delete cascade,
 email text,
 telephone text,
 segmentation text default ''::text not null,
 from_saft timestamp with time zone not null,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone
);

alter table public.saft_customers
 owner to postgres;

create index if not exists "IX_saft_customers_city"
 on public.saft_customers (city);

create index if not exists "IX_saft_customers_consumer_id"
 on public.saft_customers (consumer_id);

create index if not exists "IX_saft_customers_country"
 on public.saft_customers (country);

create index if not exists "IX_saft_customers_name"
 on public.saft_customers (name);

create table if not exists public.saft_invoices
(
 id uuid not null
 constraint "PK_saft_invoices"
 primary key,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone,
 invoice_status text not null,
 invoice_type text not null,
 date timestamp with time zone not null,
 consumer_id bigint not null
 constraint "FK_saft_invoices_consumers_consumer_id"
 references public.consumers
 on delete cascade,
 document_id bigint not null
 constraint "FK_saft_invoices_documents_document_id"
 references public.documents
 on delete cascade,
 customer_id bigint not null
 constraint "FK_saft_invoices_saft_customers_customer_id"
 references public.saft_customers
 on delete cascade
);

alter table public.saft_invoices
 owner to postgres;

create index if not exists "IX_saft_invoices_consumer_id"
 on public.saft_invoices (consumer_id);

create index if not exists "IX_saft_invoices_customer_id"
 on public.saft_invoices (customer_id);

create index if not exists "IX_saft_invoices_document_id"
 on public.saft_invoices (document_id);

create table if not exists public.saft_lines
(
 id bigint generated by default as identity
 constraint "PK_saft_lines"
 primary key,
 quantity double precision not null,
 unit_price double precision not null,
 total double precision not null,
 product_code text not null,
 invoice_id text not null,
 invoice_status text not null,
 invoice_type text not null,
 product_description text not null,
 date timestamp with time zone not null,
 month integer not null,
 year integer not null,
 consumer_id bigint not null
 constraint "FK_saft_lines_consumers_consumer_id"
 references public.consumers
 on delete cascade,
 document_id bigint not null
 constraint "FK_saft_lines_documents_document_id"
 references public.documents
 on delete cascade,
 customer_id bigint not null
 constraint "FK_saft_lines_saft_customers_customer_id"
 references public.saft_customers
 on delete cascade,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone
);

alter table public.saft_lines
 owner to postgres;

create index if not exists "IX_saft_lines_consumer_id"
 on public.saft_lines (consumer_id);

create index if not exists "IX_saft_lines_customer_id"
 on public.saft_lines (customer_id);

create index if not exists "IX_saft_lines_document_id"
 on public.saft_lines (document_id);

create index if not exists "IX_saft_lines_invoice_status"
 on public.saft_lines (invoice_status);

create index if not exists "IX_saft_lines_invoice_type"
 on public.saft_lines (invoice_type);

create index if not exists "IX_saft_lines_product_code"
 on public.saft_lines (product_code);

create index if not exists saft_lines_month_index
 on public.saft_lines (month);

create index if not exists saft_lines_year_index
 on public.saft_lines (year);

create table if not exists public.saft_products
(
 id bigint generated by default as identity
 constraint "PK_saft_products"
 primary key,
 product_code text not null,
 description text not null,
 segmentation text not null,
 consumer_id bigint not null
 constraint "FK_saft_products_consumers_consumer_id"
 references public.consumers
 on delete cascade,
 created_at timestamp with time zone not null,
 updated_at timestamp with time zone not null,
 delete_at timestamp with time zone
);

alter table public.saft_products
 owner to postgres;

create index if not exists "IX_saft_products_consumer_id"
 on public.saft_products (consumer_id);

create index if not exists saft_products_segmentation_index
 on public.saft_products (segmentation);

